---

- name: Uninstalling k3s from master
  hosts: ocarm1
  become: true
  tasks:
    - name: Removing k3s from master
      shell: /usr/local/bin/k3s-uninstall.sh

- name: Uninstalling k3s from worker
  hosts: ocarm2
  become: true
  tasks:
    - name: Removing k3s from worker
      shell: /usr/local/bin/k3s-agent-uninstall.sh

- name: Finishing
  hosts: homelab
  become: true
  tasks:
    - name: Removing install script
      file:
        path: /tmp/k3s.sh 
        state: absent

    - name: Rebooting cluster
      reboot: